# Generated by Django 4.2.3 on 2023-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('head0', models.CharField(max_length=200)),
                ('chead0', models.CharField(max_length=2000)),
                ('head1', models.CharField(max_length=200)),
                ('chead1', models.CharField(max_length=2000)),
                ('head2', models.CharField(max_length=200)),
                ('chead2', models.CharField(max_length=2000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
