# Generated by Django 4.2.3 on 2023-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_desc', models.CharField(max_length=300)),
                ('prod_pub', models.DateField()),
            ],
        ),
    ]
