# Generated by Django 4.2.3 on 2023-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_info', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
